[2020-06-14 21:13:54,456] {/home/alta7/.local/lib/python3.6/site-packages/flask/app.py:1892} ERROR - Exception on /user [PATCH]
Traceback (most recent call last):
  File "/home/alta7/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1211, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/home/alta7/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 862, in _init_compiled
    for key in compiled_params
  File "/home/alta7/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 862, in <genexpr>
    for key in compiled_params
  File "/home/alta7/.local/lib/python3.6/site-packages/sqlalchemy/sql/sqltypes.py", line 1828, in process
    value = _strict_as_bool(value)
  File "/home/alta7/.local/lib/python3.6/site-packages/sqlalchemy/sql/sqltypes.py", line 1803, in _strict_as_bool
    raise TypeError("Not a boolean value: %r" % value)
TypeError: Not a boolean value: 'True'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alta7/.local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta7/.local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta7/.local/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta7/.local/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta7/.local/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta7/.local/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 108, in wrapper
    return fn(*args, **kwargs)
  File "/home/alta7/Documents/project_griffin_backend_bu/blueprints/user/resources.py", line 105, in patch
    db.session.commit()
  File "/home/alta7/.local/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/alta7/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1042, in commit
    self.transaction.commit()
  File "/home/alta7/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 504, in commit
    self._prepare_impl()
  File "/home/alta7/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl
    self.session.flush()
  File "/home/alta7/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2523, in flush
    self._flush(objects)
  File "/home/alta7/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2664, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/alta7/.local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/alta7/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/alta7/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2624, in _flush
    flush_context.execute()
  File "/home/alta7/.local/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/alta7/.local/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/home/alta7/.local/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 236, in save_obj
    update,
  File "/home/alta7/.local/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 995, in _emit_update_statements
    statement, multiparams
  File "/home/alta7/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1020, in execute
    return meth(self, multiparams, params)
  File "/home/alta7/.local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/alta7/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_clauseelement
    distilled_params,
  File "/home/alta7/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1214, in _execute_context
    e, util.text_type(statement), parameters, None, None
  File "/home/alta7/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1518, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/alta7/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/alta7/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1211, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/home/alta7/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 862, in _init_compiled
    for key in compiled_params
  File "/home/alta7/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 862, in <genexpr>
    for key in compiled_params
  File "/home/alta7/.local/lib/python3.6/site-packages/sqlalchemy/sql/sqltypes.py", line 1828, in process
    value = _strict_as_bool(value)
  File "/home/alta7/.local/lib/python3.6/site-packages/sqlalchemy/sql/sqltypes.py", line 1803, in _strict_as_bool
    raise TypeError("Not a boolean value: %r" % value)
sqlalchemy.exc.StatementError: (builtins.TypeError) Not a boolean value: 'True'
[SQL: UPDATE user SET is_publisher=%(is_publisher)s, salt=%(salt)s, updated_at=%(updated_at)s WHERE user.id = %(user_id)s]
[parameters: [{'updated_at': datetime.datetime(2020, 6, 14, 21, 13, 54, 456003), 'salt': '0a64298588a24a9fb0dba8fe1a87432d', 'is_publisher': 'True', 'user_id': 3}]]
[2020-06-14 21:13:54,458] {/home/alta7/Documents/project_griffin_backend_bu/blueprints/__init__.py:79} ERROR - REQUEST_LOG	{"method": "PATCH", "code": "500 INTERNAL SERVER ERROR", "uri": "/user?", "request": {"is_publisher": true}, "response": {"message": "Internal Server Error"}}
[2020-06-14 21:14:58,209] {/home/alta7/Documents/project_griffin_backend_bu/blueprints/__init__.py:69} WARNING - REQUEST_LOG	{"method": "PATCH", "code": "200 OK", "uri": "/user?", "request": {"name": "Joni"}, "response": {"id": 3, "name": "Joni", "phone": "081321324324", "email": "jati@gmail.com", "user_type": "user", "is_publisher": false, "password": "359e2669bfc07daea53e70999e0b656e4f4f98f92f55e66f83544498a65260a761667ade3a1f704529d554ba18e0086885b83c339920527f0cdd79d584ba0f3f", "created_at": "Sun, 14 Jun 2020 20:36:02 -0000", "updated_at": "Sun, 14 Jun 2020 21:14:58 -0000"}}
[2020-06-14 21:15:50,655] {/home/alta7/Documents/project_griffin_backend_bu/blueprints/__init__.py:69} WARNING - REQUEST_LOG	{"method": "PATCH", "code": "200 OK", "uri": "/user?", "request": {"is_publisher": true}, "response": {"id": 3, "name": "Joni", "phone": "081321324324", "email": "jati@gmail.com", "user_type": "user", "is_publisher": true, "password": "359e2669bfc07daea53e70999e0b656e4f4f98f92f55e66f83544498a65260a761667ade3a1f704529d554ba18e0086885b83c339920527f0cdd79d584ba0f3f", "created_at": "Sun, 14 Jun 2020 20:36:02 -0000", "updated_at": "Sun, 14 Jun 2020 21:15:51 -0000"}}
[2020-06-14 21:18:31,074] {/home/alta7/Documents/project_griffin_backend_bu/blueprints/__init__.py:69} WARNING - REQUEST_LOG	{"method": "PATCH", "code": "200 OK", "uri": "/user?", "request": {"name": "Jaka", "phone": "098123456789", "email": "jaka@gmail.com"}, "response": {"id": 3, "name": "Jaka", "phone": "098123456789", "email": "jaka@gmail.com", "user_type": "user", "is_publisher": true, "password": "359e2669bfc07daea53e70999e0b656e4f4f98f92f55e66f83544498a65260a761667ade3a1f704529d554ba18e0086885b83c339920527f0cdd79d584ba0f3f", "created_at": "Sun, 14 Jun 2020 20:36:02 -0000", "updated_at": "Sun, 14 Jun 2020 21:18:31 -0000"}}
[2020-06-14 21:19:07,566] {/home/alta7/Documents/project_griffin_backend_bu/blueprints/__init__.py:69} WARNING - REQUEST_LOG	{"method": "PATCH", "code": "200 OK", "uri": "/user?", "request": {"password": "biasa"}, "response": {"id": 3, "name": "Jaka", "phone": "098123456789", "email": "jaka@gmail.com", "user_type": "user", "is_publisher": true, "password": "981736c3371bebd4ac24c1d4a02b97677770a9509ef0848283adfe80edb04aa36fcf50d95cbb6dc820e6982b5036cb09c951cbb4363826e6692a3eb9b2324316", "created_at": "Sun, 14 Jun 2020 20:36:02 -0000", "updated_at": "Sun, 14 Jun 2020 21:19:08 -0000"}}
[2020-06-14 21:20:43,197] {/home/alta7/Documents/project_griffin_backend_bu/blueprints/__init__.py:79} ERROR - REQUEST_LOG	{"method": "DELETE", "code": "404 NOT FOUND", "uri": "/user/2?", "request": null, "response": {"status": "NOT_FOUND"}}
[2020-06-14 21:20:51,462] {/home/alta7/Documents/project_griffin_backend_bu/blueprints/__init__.py:69} WARNING - REQUEST_LOG	{"method": "DELETE", "code": "200 OK", "uri": "/user/4?", "request": null, "response": {"status": "DELETED"}}
